# Generated by Django 4.1.4 on 2022-12-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=300)),
                ('teacheremail', models.CharField(max_length=200)),
                ('teachermobile', models.IntegerField()),
                ('joindate', models.DateField()),
                ('education', models.CharField(max_length=200)),
                ('workexp', models.CharField(max_length=200)),
                ('ctc', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
